-- AlterTable
ALTER TABLE "Deck" ALTER COLUMN "description" SET DEFAULT '',
ALTER COLUMN "topics" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "studyProgress" SET DEFAULT 0,
ALTER COLUMN "accuracy" SET DEFAULT 0,
ALTER COLUMN "lastStudied" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isStarred" SET DEFAULT false;
